version: '3.7'
services:
  postgres:
    image: postgres:15beta2-bullseye
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=PrivetHello
    - POSTGRES_DB=app
    - POSTGRES_USER=admin